FROM nvcr.io/nvidia/cuda:11.7.1-base-ubuntu22.04 as base
# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

ENV DEBIAN_FRONTEND=noninteractive 
# runtime dependencies
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libbluetooth-dev \
		tk-dev \
		uuid-dev \
                git \
                curl \
                python3 \
                python3-pip \
                vim \
                build-essential \
                gfortran \
                python3-poetry \
                python3-dev \
	; \
	rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/wezzels/pycheron.git
RUN curl -sSL https://install.python-poetry.org -o install.py
RUN chmod +X install.py &&  POETRY_VERSION=1.1.15 python3 ./install.py
RUN mkdir -p /root/.local/bin
RUN mkdir -p /root/.local/share/pypoetry/venv/bin
RUN mkdir -p /root/.local/share/pypoetry/venv/bin
RUN mv /root/.local/bin/poetry /usr/local/bin/ && poetry --version
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN  set -eux; \
        apt-get update; \
        apt-get -y --no-install-recommends install git-lfs \
        ; \
        rm -rf /var/lib/apt/lists/*
RUN cd pycheron && git lfs install && git lfs fetch && git lfs pull
WORKDIR /pycheron
RUN ./build.sh
RUN mv /pycheron/dist/pycheron-3.0.0-py2.py3-none-any.whl /opt/
WORKDIR /opt/
COPY pycheron_test ./
COPY callPycheronMetric_tutorial_config.yaml ./
RUN pip3 install toml
RUN pip3 install dash 
RUN pip3 install joblib
RUN pip3 install sklearn
RUN pip3 install pathlib2
RUN pip3 install hampel
RUN pip3 install numba
RUN pip3 install future
RUN pip3 install cx_Oracle
RUN pip3 install numpy
RUN pip3 install pisces sqlalchemy==1.3.24
RUN pip3 install pebble
RUN pip3 install setuptools
RUN pip3 install pandas 
RUN pip3 install statsmodels
RUN pip3 install pyaml

RUN pip3 install /opt/pycheron-3.0.0-py2.py3-none-any.whl&& rm -rf /opt/pycheron-3.0.0-py2.py3-none-any.whl
CMD ["bash"]
#CMD ["/usr/bin/python3 /pycheron/pycheron/callPycheronMetric.py /opt/callPycheronMetric_tutorial_config.yaml"]
